### ISSUE TITLE
Running Alex via Travis CI throws an exception

### ISSUE THREAD

**Issue by actionjack** [wooorm/alex#171]
When I added alex --diff to my `travis.yml` Travis CI threw up the following error:

```
0.07s$ alex --diff
/home/travis/build/actionjack/so-you-want-to-onboard-a-devops-engineer/node_modules/alex/node_modules/update-notifier/index.js:2
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/actionjack/so-you-want-to-onboard-a-devops-engineer/node_modules/alex/cli.js:14:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
The command "alex --diff" exited with 8.
```

**Comment by wooorm** [comment]
I think this should be okay if you use a newer version of node in travis (where `const` is supported). Could you check if that works?

**Comment by actionjack** [comment]
Yep that works when I use node 6.0.0 thanks

**Comment by wooorm** [comment]
Great! Thanks for using alex :)
